# Generated by Django 6.0.3 on 2026-04-26 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riscos", "0002_risco_status_datas"),
        ("tratamentos", "0001_initial"),
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tratamento",
            name="data_atualizacao",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tratamento",
            name="data_criacao",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tratamento",
            name="risco",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="riscos.risco",
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="tratamento",
            name="usuario_responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="usuario.usuario",
                null=True,
                blank=True,
            ),
        ),
    ]
