# Generated by Django 6.0.5 on 2026-06-14 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riscos', '0002_risco_status_datas'),
        ('tratamentos', '0002_tratamento_data_atualizacao_tratamento_data_criacao_and_more'),
        ('usuario', '0002_usuario_ativo_usuario_centro_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='acao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='resposta',
            field=models.CharField(choices=[('mitigar', 'Mitigar / Reduzir'), ('evitar', 'Evitar'), ('transferir', 'Transferir'), ('aceitar', 'Aceitar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='risco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='riscos.risco'),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='situacao',
            field=models.CharField(choices=[('nao_iniciado', 'Não Iniciado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('suspenso', 'Suspenso')], default='nao_iniciado', max_length=50),
        ),
        migrations.AlterField(
            model_name='tratamento',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuario'),
        ),
    ]
