# Generated by Django 6.0.5 on 2026-06-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_ativo_usuario_centro_usuario_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Diretor', 'Diretor'), ('Coordenador', 'Coordenador'), ('Analista', 'Analista'), ('Técnico', 'Técnico'), ('Professor', 'Professor'), ('Servidor', 'Servidor')], max_length=100),
        ),
    ]
