# Generated by Django 6.0.3 on 2026-04-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('riscos_operacionais', 'Riscos Operacionais'), ('riscos_de_imagem_reputacao', 'Riscos de Imagem/Reputação'), ('riscos_legais', 'Riscos Legais'), ('riscos_financeiros_orcamentarios', 'Riscos Financeiros/Orçamentários')], max_length=50)),
                ('departamento', models.CharField(max_length=100)),
                ('impacto', models.CharField(max_length=50)),
                ('probabilidade', models.CharField(max_length=50)),
                ('nivel_de_risco', models.CharField(max_length=50)),
                ('eficacia_dos_controles', models.CharField(max_length=50)),
                ('nivel_residual', models.CharField(max_length=50)),
            ],
        ),
    ]
