# Generated by Django 6.0.5 on 2026-06-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riscos', '0002_risco_status_datas'),
    ]

    operations = [
        migrations.AddField(
            model_name='risco',
            name='impacto_residual',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='risco',
            name='probabilidade_residual',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='risco',
            name='nivel_residual',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
